targets:
  $default:
    builders:
      get_internationalization|internationalization:
        generate_for:
          - lib/**/*.dart
          - example/*.dart

builders:
  internationalization:
    import: "package:get_internationalization/src/internationalization_builder.dart"
    builder_factories: ["internationalizationBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
    runs_before: ["source_gen|combining_builder"]