name: internationalization
description: A Dart package for generating internationalization files from annotated classes.

version: 0.0.1
homepage: https://github.com/manukj/internationalization
repository: https://github.com/manukj/internationalization
issue_tracker: https://github.com/manukj/internationalization/issues


environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  analyzer: ^5.12.0
  build: ^2.0.0
  source_gen: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0