name: lang_internationalization
description: A Dart package for generating lang_internationalization files from annotated classes.

version: 0.0.5
homepage: https://github.com/manukj/lang_internationalization
repository: https://github.com/manukj/lang_internationalization
issue_tracker: https://github.com/manukj/lang_internationalization/issues


environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  build: ^2.0.0
  source_gen: ^1.0.0
  analyzer: ^6.3.0 

dev_dependencies:
  build_runner: ^2.4.9